name: Deploy Portal to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Home Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server via SSH
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/like/apps/portal-home-like
          git pull origin main
          cd /home/like/apps/
          docker compose down server-portal
          docker compose up -d --build server-portal
        EOF
