name: Deploy Portal to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Home Server
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to server
      run: |
        cd /home/like/apps/portal-home-like
        git pull origin main
        cd /home/like/apps
        docker compose up -d --build server-portal
